# Generated by Django 3.2.6 on 2021-08-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0003_auto_20210816_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cds',
            new_name='cds_model',
        ),
    ]
