# Generated by Django 3.2.6 on 2021-08-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0005_alter_cds_model_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cds_model',
            name='date',
        ),
    ]
