# Generated by Django 3.2.6 on 2021-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cds', '0006_remove_cds_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cds_model',
            name='date',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
